api_platform:
    title: API Gestion Espace de Travail
    description: API REST construit avec Symfony, API Platform, Doctrine ORM et JWT pour l'authentification. Elle permet de gérer les espaces de travail, salles de réunion, bureaux, réservations, utilisateurs, équipement, ect.
    version: 1.0.0
    defaults:
        stateless: true
        pagination_items_per_page: 10
        maximum_items_per_page: 100
        cache_headers:
            max_age: 3600
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin', 'Accept-Language']
    formats:
        json:
            mime_types: [ 'application/json' ]
        jsonld:
            mime_types: [ 'application/ld+json' ]
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header