name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: Symfony_EspaceTravailAPI_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      APP_ENV: test
      APP_SECRET: $ecretf0rt3st
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/Symfony_EspaceTravailAPI
      JWT_SECRET_KEY: config/jwt/private.pem
      JWT_PUBLIC_KEY: config/jwt/public.pem
      JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create database
        env:
          APP_ENV: test
        run: php bin/console doctrine:database:create --if-not-exists --env=test

      - name: Check for migrations
        run: |
          if [ -z "$(ls -A migrations/)" ]; then
            echo "No migrations found, skipping migration step.";
            exit 0;
          fi

      - name: Run database migrations
        env:
          APP_ENV: test
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --level=max src/

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff